dataset_name: "shd"
subdirectory: "SHD" 
bin_size_ms: 4.0
num_channels: 700
max_time_ms: 1000.0
train_file_name: "shd_train.h5"
test_file_name: "shd_test.h5"
batch_size: 256
input_dim: ${dataset.num_channels}
num_classes: 20
ignore_first_n_timesteps: 50
clip_to_1: false
seed: ${seed}